### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by spences10** [jkol36/instagrambot#1]
Hey buddy, nice looking bot :+1: 

Just wondering why you don't use `.env` [`require('dotenv')`] for your config of `headers` bit risky having someone else useing your Insta account details if they wanted to

Also, can you detail how you get this information?

**Comment by jkol36** [comment]
@spences10 good point man. I should change that. I'll change that in a commit. As for the headers, if you go to instagram.com in your browser, login, then open up the chrome dev tools => click on network => preserve log => click the xhr tab => and then hit any of the requests, you'll see the headers there. You can click copy as curl and paste that into https://curl.trillworks.com/ and you should be good to go.

**Comment by spences10** [comment]
I'll take a look, thanks mate :+1:
